### ISSUE TITLE
Displaying a form for authenticated user

### ISSUE THREAD

**Issue by ogirardot** [django-fluent/django-fluent-comments#9]
Hi, 
is there any way to display just the necessary fields to allow only authenticated users to post comments.
Django's comments framework documentation is not very precise about this https://docs.djangoproject.com/en/dev/ref/contrib/comments/#providing-a-comment-form-for-authenticated-users 
Any idea on how to use that with both crispy and your project ?

Regards, 

Olivier.

**Comment by gustavklopp** [comment]
This feature would be great! I'm still struggling to get it working.

 >this can be controlled via de "allow" hook in the moderator class (to stop the POST request), and hide the fields by simply not displaying them in the Django HTML template.
May I ask you to detail a bit as you do it?

I've tried something like:
```
   {% csrf_token %}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}

  <div class="form-group">
    <label for="{{ form.comment.id_for_label }}">Your Comment:</label>
        {{ form.comment }}
  </div>
  <div class="form-group">
    <label class="class_honeypot" for="{{ form.honeypot.id_for_label }}">If you enter anything in this field your comment will be treated as spam:</label>
    {{ form.honeypot }}
  </div>
    <button class="btn btn-default" type="submit"  value="Post" name="post" id="id_submit">Post comment</button>
    <button class="btn btn-default" type="submit" value="Preview" name="preview">Preview</button>
```
But it's not working: Comment is not posted, there's no error, but clicking on the "submit" button does nothing.

**Comment by gustavklopp** [comment]
Sorry for the question!

I've just fallen on https://github.com/edoburu/django-fluent-comments#hiding-form-fields and it's now working!

**Comment by pembeci** [comment]
I didn't activate manager functionality so here is my workaround. Subclassing the form doesn't work because we don't have the request object. Another option was instead of printing the form as whole printing its fields one by one in the template, but I don't know how to do that with crispy. So what I did was modify the `form.html` template and put the following at the end of it:
```javascript
{% if request.user.is_authenticated %}
  <script>
    const inputName = document.querySelector(".comments-form input[name=name]");
    inputName.value = "{{ request.user.first_name }}";
    inputName.disabled = true;
    const inputEmail = document.querySelector(".comments-form input[name=email]");
    inputEmail.value = "{{ request.user.email }}";
    inputEmail.disabled = true;
  </script>
{% endif %}  
```
We wouldn't have jquery loaded at this point so we use the native methods. We can put this in a static js file instead of a template but then we need to pass the user object to that file so for now I solved it like this.
